language: python

python:
  - "2.7"
  - "3.5"

install:
  - sudo apt-get -qq update
  - sudo apt-get install g++
  - pip install -r requirements.txt
  - pip install .

script:
  - python -m unittest discover tests/
