language: python

install:
  - sudo apt-get -qq update
  - sudo apt-get install swig
  - sudo apt-get install g++
  - pip install -r requirements.txt
  - pip install .

script:
  - python -m unittest discover tests/
