language: python

install:
  - sudo apt-get -qq update
  - sudo apt-get install swig3.0
  - sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
  - sudo ln -s /usr/lib/python2.7/dist-packages/numpy/core/include/numpy /usr/include/numpy
  - sudo apt-get install g++
  - sudo apt-get install mpich2
  - pip install -r requirements.txt
  - pip install .

script:
  - python -m unittest discover tests/
  - py.test examples/ -v
